version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:8.9.2
    ports:
      - "9200"
    environment:
      - ES_JAVA_OPTS=-Xms128M -Xmx128M
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
    hostname: es
    networks:
      - gcTour

  mariadb:
    image: mariadb:10.11.5-jammy
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gctour
      MARIADB_AUTO_UPGRADE: true
    hostname: mariadb
    networks:
      - gcTour
    command: --collation-server=utf8mb4_unicode_ci --character-set-server=utf8mb4

  redis:
    image: redis:7.0.12-alpine
    ports:
      - "6379"
    hostname: redis
    networks:
      - gcTour

  clickhouse:
    image: clickhouse/clickhouse-server:23.4.2.11-alpine
    ports:
      - "8123"
      - "9000"
    hostname: clickhouse
    networks:
      - gcTour

networks:
  gcTour:
