name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: hub.scireum.com/scireum/sirius-build:latest
    steps:
      - name: checkout project
        uses: actions/checkout@v1
      - name: build gcTour
        run: mvn clean package -DskipTests
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.KEY }}
          registry: docker.pkg.github.com
          repository: gctour/gctour/gctour
          tag_with_ref: true