name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: scireum/sirius-build-jdk18:4.1
    steps:
      - name: checkout project
        uses: actions/checkout@v1
        
      - name: build gcTour
        run: mvn clean package
     
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: gctour
          password: ${{ secrets.KEY }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.pkg.github.com/gctour/gctour/gctour:latest
