name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: hub.scireum.com/scireum/sirius-build:latest
    steps:
      - name: checkout project
        uses: actions/checkout@v1
      - name: build gcTour
        run: mvn clean package -DskipTests
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: gctour/gctour/gctour:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.KEY }}
          registry: docker.pkg.github.com